### ISSUE TITLE
[Feature]:

### ISSUE THREAD

**Issue by aleopardstail** [Simpit-team/KerbalSimpitRevamped#78] opened 2022-02-01 19:58 UTC
## Is your feature request related to a problem? Please describe.
not a problem as such, but a desire to see what the game thinks the user input is and to see what the game wishes to do prior to user input - the goal is to all feedback on controller, either visual or physical
<br>

### A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
currently the player can send messages to set the control axis, including the throttle, but has no way of knowing what value actually is set - e.g. when mechjeb is flying the control axis and throttle will adjust but there is no way to show this on a controller
<br>

### What is the issue that you are facing, that you would like resolved? How would it benefit players?
situations where autopilot or game input (mechjeb or SAS) change control axis do not provide feedback - this can be seen on screen but it would be ideal to have all axis and throttles available to a controller
<br>

### Is it an existing/new feature in the game that would benefit from support by this mod?
think this is just existing stuff
<br>

### A clear and concise description of what you want to happen.
the addition of several message channels to which a controller can subscribe - so that as well as being able to send a rotationMessage, it is possible to request a rotationMessage to be sent back - ideally two such, one for before the player input is added and one for after the player input is added.

this for the following
- rotationMessage
- translationMessage
- customAxisMessage
- wheelMessage
- throttleMessage

<br>

### How would it be best that the feature is implemented? What sort of data may need to be sent by the mod to controllers? Would it require a digital signal, or an analogue one? Maybe it needs a terminal command to help use it, or a GUI button?

pure channel registration to request feedback on the above message channels, no UI changes required

suggest the data is captured in the code that performs the adjustments, before and after, then as usual only sent if something has changed

<br>

### 

## Describe alternatives you've considered
<br>

### A clear and concise description of any alternative solutions or features you've considered.
storing the values sent locally sort of works but is not ideal as there is no way to reflect say what mechJeb of SAS is doing
<br>

### What about the current features of the program do not quite, if at all, allow you to implement/carry out what you would like to do? 
<br>

### What is the nearest feature in the mod (If there is one), that is along the lines of what you are suggesting?
pretty much any of the outbound messages e.g. flight status, fuel levels etc
<br>

## Additional context
<br>

**Comment by PBechon** [comment] 2022-05-07 20:50
Seem to be a duplicate of #79. I suggest closing this one and keeping only the other one

**Closed by PBechon** 2022-05-07 20:50 UTC
