### ISSUE TITLE
[BUG]: Handshake loops for a while/forever

### ISSUE THREAD

**Issue by fgaudin** [Simpit-team/KerbalSimpitRevamped#63] opened 2021-09-09 05:30 UTC
- Mod version: v2-alpha6 + fix of 9/7/21 uploaded on Discord by Rogor
- Game version: 1.12.2
- Operating system: Windows 10
- Microprocessor/s in use: Intel I5

First connection is working but generally after closing the connection on the KSP side, uploading new code to the Arduino or just resetting it and reopening the connection, the handshake loops on "KerbalSimpit: SYN received on port COM3. Replying."

## Experimentations
I had two Arduinos configured, removed one from the config and now testing on a bare Arduino connected through a a USB hub.
It seems to work out when no channels are subscribed to but if there are multiple channels, it will start looping. Commenting out all channels won't make it better if the handshake hasn't recovered.

## How repeatable is it?
it works on the first connection, usually start looping a few seconds after a few close/start and then it seems to get worse to the point of not even recovering after a while

## To Reproduce

I can reproduce fairly easily with the following pattern:
- connect successfully
- close connection KSP
- reset Arduino with or without modification
- wait a few seconds
- start connection in KSP

List of channels subscribed:
```
mySimpit.registerChannel(ALTITUDE_MESSAGE);
mySimpit.registerChannel(ACTIONSTATUS_MESSAGE);
mySimpit.registerChannel(LF_STAGE_MESSAGE);
mySimpit.registerChannel(OX_STAGE_MESSAGE);
mySimpit.registerChannel(XENON_GAS_STAGE_MESSAGE);
mySimpit.registerChannel(MONO_MESSAGE);
mySimpit.registerChannel(ELECTRIC_MESSAGE);
mySimpit.registerChannel(FLIGHT_STATUS_MESSAGE);
mySimpit.registerChannel(CAGSTATUS_MESSAGE);
mySimpit.registerChannel(APSIDES_MESSAGE);
mySimpit.registerChannel(VELOCITY_MESSAGE);
mySimpit.registerChannel(TACLS_RESOURCE_MESSAGE);
mySimpit.registerChannel(TACLS_WASTE_MESSAGE);
mySimpit.registerChannel(APSIDESTIME_MESSAGE);
mySimpit.registerChannel(ORBIT_INFO);
mySimpit.registerChannel(MANEUVER_MESSAGE);
```

actual code (removed all the commented code of my controller).
```
#include <Arduino.h>
#include <SoftwareSerial.h>
#include <KerbalSimpit.h>

#define DEBUG 1
#define TEST 0

const int pinDebugRx = 6;
const int pinDebugTx = 7;

SoftwareSerial Serial1(pinDebugRx, pinDebugTx); // RX, TX

KerbalSimpit mySimpit(Serial, Serial1);

void setup()
{
  Serial.begin(115200);
  Serial1.begin(38400);

  Serial1.println("debugging on");

  // simpit
  while (!mySimpit.init()) {
    delay(100);
  }
  mySimpit.printToKSP("Connected 3.10", PRINT_TO_SCREEN);
  
  mySimpit.inboundHandler(messageHandler);
  mySimpit.registerChannel(ALTITUDE_MESSAGE);
  mySimpit.registerChannel(ACTIONSTATUS_MESSAGE);
  mySimpit.registerChannel(LF_STAGE_MESSAGE);
  mySimpit.registerChannel(OX_STAGE_MESSAGE);
  mySimpit.registerChannel(XENON_GAS_STAGE_MESSAGE);
  mySimpit.registerChannel(MONO_MESSAGE);
  mySimpit.registerChannel(ELECTRIC_MESSAGE);
  mySimpit.registerChannel(FLIGHT_STATUS_MESSAGE);
  mySimpit.registerChannel(CAGSTATUS_MESSAGE);
  mySimpit.registerChannel(APSIDES_MESSAGE);
  mySimpit.registerChannel(VELOCITY_MESSAGE);
  mySimpit.registerChannel(TACLS_RESOURCE_MESSAGE);
  mySimpit.registerChannel(TACLS_WASTE_MESSAGE);
  mySimpit.registerChannel(APSIDESTIME_MESSAGE);
  mySimpit.registerChannel(ORBIT_INFO);
  mySimpit.registerChannel(MANEUVER_MESSAGE);
}

void loop() {
  mySimpit.update();
}
```

I modified KerbalSimpit.cpp to take another serial stream so I can send logs to another Arduino using pin 6 and 7 (connected respectively to 3 and 2 on the other Arduino running https://github.com/fgaudin/ArduinoDebugger)
```
bool KerbalSimpit::init()
{
  if (_serial == NULL) {
    return false;
  }
  _outboundBuffer[0] = 0x00;
  int i;
  for (i=0; i<sizeof(KERBALSIMPIT_VERSION); i++) {
    _outboundBuffer[i+1] = KERBALSIMPIT_VERSION[i];
  }
  i = i + 1;
  _receiveState = WaitingFirstByte;
  _serialDbg->println("sending SYN");
  _send(0x00, _outboundBuffer, i); // Send SYN

  uint8_t count = 0;
  
  _serialDbg->println("waiting for data");
  while (!_serial->available()){
    _serialDbg->println("not available");
    count += 1;
    delay(100);
    if(count > 10){
      return false;  
    }
  }
  int b;
  _serialDbg->println("Reading first byte");
  b = _serial->read();
  _serialDbg->println(b, HEX);
  if (b == 0xAA) { // First byte of header
    _serialDbg->println("First byte of header received");
    while (!_serial->available());
    _serialDbg->println("Reading second byte");
    b = _serial->read();
    _serialDbg->println(b, HEX);
    if (b == 0x50) { // Second byte of header
      _serialDbg->println("Second byte of header received");
      while (!_serial->available());
      _serialDbg->println("reading size");
      b = _serial->read(); // size
      _serialDbg->println(b, HEX);
      while (!_serial->available());
      _serialDbg->println("reading type");
      b = _serial->read();
      _serialDbg->println(b, HEX);
      if (b == 0x00) { // type
        _serialDbg->println("type == 0x00");
        while (!_serial->available());
        _serialDbg->println("payload ready");
        if (_serial->read() == 0x01) { // first byte of payload, we got a SYNACK
          _serialDbg->println("received SYNACK");
          // TODO: Do we care about tracking handshake state?
          _outboundBuffer[0] = 0x02;
          _send(0x00, _outboundBuffer, i); // Send ACK
          _serialDbg->println("sent ACK, success");
          return true;
        }
      }
    }
  }
  _serialDbg->println("sync failed");
  return false;
}
```

Here's one sample of the logs:
[platformio-device-monitor-210908-213819.log](https://github.com/Simpit-team/KerbalSimpitRevamped/files/7133645/platformio-device-monitor-210908-213819.log)

**Comment by PBechon** [comment] 2021-09-09 20:36
I had a similar issue sometimes but I was not able to reproduce it consistently.

I have added a clearing of the sending when a handshake start in c30c73a086d519edc920458aaac60ed1c9c76b40
I have improved the init code on the Arduino lib to read all packets received and look for a SYNACK in it instead of just looking at the first one.

Can you see if the problem is solved ? For convenience, I attached the DLL as compiled with the commit mentioned above and the new KerbalSimpit.cpp as committed in the Arduino repo.

[KerbalSimpit_20210909.zip](https://github.com/Simpit-team/KerbalSimpitRevamped/files/7139617/KerbalSimpit_20210909.zip)

**Comment by PBechon** [comment] 2021-09-15 20:57
This issue appears to be fixed by those commits.

**Closed by PBechon** 2021-09-15 20:57 UTC
